---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: molecule-centos6
    image: centos:6
  - name: molecule-centos7
    image: centos:7
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
  - name: molecule-ubuntu1604
    image: ubuntu:xenial
  - name: molecule-ubuntu1804
    image: ubuntu:bionic
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=60s
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
